/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as ColdStorageRouteImport } from './routes/cold-storage'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CropCalendarRouteImport } from './routes/crop-calendar'
import { Route as CropInsuranceRouteImport } from './routes/crop-insurance'
import { Route as InternshipsRouteImport } from './routes/internships'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MachinesToolsRouteImport } from './routes/machines-tools'
import { Route as MarketRouteImport } from './routes/market'
import { Route as MarketPricesRouteImport } from './routes/market-prices'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MyApplicationsRouteImport } from './routes/my-applications'
import { Route as MyCoursesRouteImport } from './routes/my-courses'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrderRouteImport } from './routes/order'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as SupportRouteImport } from './routes/support'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as MachinesToolsListRouteImport } from './routes/machines-tools.list'
import { Route as ProductIdRouteImport } from './routes/product/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const ColdStorageRoute = ColdStorageRouteImport.update({
  id: '/cold-storage',
  path: '/cold-storage',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CropCalendarRoute = CropCalendarRouteImport.update({
  id: '/crop-calendar',
  path: '/crop-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CropInsuranceRoute = CropInsuranceRouteImport.update({
  id: '/crop-insurance',
  path: '/crop-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsRoute = InternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesToolsRoute = MachinesToolsRouteImport.update({
  id: '/machines-tools',
  path: '/machines-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketPricesRoute = MarketPricesRouteImport.update({
  id: '/market-prices',
  path: '/market-prices',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MyApplicationsRoute = MyApplicationsRouteImport.update({
  id: '/my-applications',
  path: '/my-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCoursesRoute = MyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesToolsListRoute = MachinesToolsListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => MachinesToolsRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/certificates': typeof CertificatesRoute
  '/cold-storage': typeof ColdStorageRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/crop-calendar': typeof CropCalendarRoute
  '/crop-insurance': typeof CropInsuranceRoute
  '/internships': typeof InternshipsRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/machines-tools': typeof MachinesToolsRouteWithChildren
  '/market': typeof MarketRoute
  '/market-prices': typeof MarketPricesRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-applications': typeof MyApplicationsRoute
  '/my-courses': typeof MyCoursesRoute
  '/notifications': typeof NotificationsRoute
  '/order': typeof OrderRoute
  '/register': typeof RegisterRoute
  '/schemes': typeof SchemesRoute
  '/seller': typeof SellerRoute
  '/support': typeof SupportRoute
  '/weather': typeof WeatherRoute
  '/machines-tools/list': typeof MachinesToolsListRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/certificates': typeof CertificatesRoute
  '/cold-storage': typeof ColdStorageRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/crop-calendar': typeof CropCalendarRoute
  '/crop-insurance': typeof CropInsuranceRoute
  '/internships': typeof InternshipsRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/machines-tools': typeof MachinesToolsRouteWithChildren
  '/market': typeof MarketRoute
  '/market-prices': typeof MarketPricesRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-applications': typeof MyApplicationsRoute
  '/my-courses': typeof MyCoursesRoute
  '/notifications': typeof NotificationsRoute
  '/order': typeof OrderRoute
  '/register': typeof RegisterRoute
  '/schemes': typeof SchemesRoute
  '/seller': typeof SellerRoute
  '/support': typeof SupportRoute
  '/weather': typeof WeatherRoute
  '/machines-tools/list': typeof MachinesToolsListRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/certificates': typeof CertificatesRoute
  '/cold-storage': typeof ColdStorageRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/crop-calendar': typeof CropCalendarRoute
  '/crop-insurance': typeof CropInsuranceRoute
  '/internships': typeof InternshipsRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/machines-tools': typeof MachinesToolsRouteWithChildren
  '/market': typeof MarketRoute
  '/market-prices': typeof MarketPricesRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-applications': typeof MyApplicationsRoute
  '/my-courses': typeof MyCoursesRoute
  '/notifications': typeof NotificationsRoute
  '/order': typeof OrderRoute
  '/register': typeof RegisterRoute
  '/schemes': typeof SchemesRoute
  '/seller': typeof SellerRoute
  '/support': typeof SupportRoute
  '/weather': typeof WeatherRoute
  '/machines-tools/list': typeof MachinesToolsListRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/certificates'
    | '/cold-storage'
    | '/contact'
    | '/courses'
    | '/crop-calendar'
    | '/crop-insurance'
    | '/internships'
    | '/learn'
    | '/login'
    | '/machines-tools'
    | '/market'
    | '/market-prices'
    | '/marketplace'
    | '/my-applications'
    | '/my-courses'
    | '/notifications'
    | '/order'
    | '/register'
    | '/schemes'
    | '/seller'
    | '/support'
    | '/weather'
    | '/machines-tools/list'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/certificates'
    | '/cold-storage'
    | '/contact'
    | '/courses'
    | '/crop-calendar'
    | '/crop-insurance'
    | '/internships'
    | '/learn'
    | '/login'
    | '/machines-tools'
    | '/market'
    | '/market-prices'
    | '/marketplace'
    | '/my-applications'
    | '/my-courses'
    | '/notifications'
    | '/order'
    | '/register'
    | '/schemes'
    | '/seller'
    | '/support'
    | '/weather'
    | '/machines-tools/list'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/certificates'
    | '/cold-storage'
    | '/contact'
    | '/courses'
    | '/crop-calendar'
    | '/crop-insurance'
    | '/internships'
    | '/learn'
    | '/login'
    | '/machines-tools'
    | '/market'
    | '/market-prices'
    | '/marketplace'
    | '/my-applications'
    | '/my-courses'
    | '/notifications'
    | '/order'
    | '/register'
    | '/schemes'
    | '/seller'
    | '/support'
    | '/weather'
    | '/machines-tools/list'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  CertificatesRoute: typeof CertificatesRoute
  ColdStorageRoute: typeof ColdStorageRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  CropCalendarRoute: typeof CropCalendarRoute
  CropInsuranceRoute: typeof CropInsuranceRoute
  InternshipsRoute: typeof InternshipsRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  MachinesToolsRoute: typeof MachinesToolsRouteWithChildren
  MarketRoute: typeof MarketRoute
  MarketPricesRoute: typeof MarketPricesRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MyApplicationsRoute: typeof MyApplicationsRoute
  MyCoursesRoute: typeof MyCoursesRoute
  NotificationsRoute: typeof NotificationsRoute
  OrderRoute: typeof OrderRoute
  RegisterRoute: typeof RegisterRoute
  SchemesRoute: typeof SchemesRoute
  SellerRoute: typeof SellerRoute
  SupportRoute: typeof SupportRoute
  WeatherRoute: typeof WeatherRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cold-storage': {
      id: '/cold-storage'
      path: '/cold-storage'
      fullPath: '/cold-storage'
      preLoaderRoute: typeof ColdStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-calendar': {
      id: '/crop-calendar'
      path: '/crop-calendar'
      fullPath: '/crop-calendar'
      preLoaderRoute: typeof CropCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-insurance': {
      id: '/crop-insurance'
      path: '/crop-insurance'
      fullPath: '/crop-insurance'
      preLoaderRoute: typeof CropInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships': {
      id: '/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof InternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines-tools': {
      id: '/machines-tools'
      path: '/machines-tools'
      fullPath: '/machines-tools'
      preLoaderRoute: typeof MachinesToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-prices': {
      id: '/market-prices'
      path: '/market-prices'
      fullPath: '/market-prices'
      preLoaderRoute: typeof MarketPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-applications': {
      id: '/my-applications'
      path: '/my-applications'
      fullPath: '/my-applications'
      preLoaderRoute: typeof MyApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-courses': {
      id: '/my-courses'
      path: '/my-courses'
      fullPath: '/my-courses'
      preLoaderRoute: typeof MyCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines-tools/list': {
      id: '/machines-tools/list'
      path: '/list'
      fullPath: '/machines-tools/list'
      preLoaderRoute: typeof MachinesToolsListRouteImport
      parentRoute: typeof MachinesToolsRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MachinesToolsRouteChildren {
  MachinesToolsListRoute: typeof MachinesToolsListRoute
}

const MachinesToolsRouteChildren: MachinesToolsRouteChildren = {
  MachinesToolsListRoute: MachinesToolsListRoute,
}

const MachinesToolsRouteWithChildren = MachinesToolsRoute._addFileChildren(
  MachinesToolsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  CertificatesRoute: CertificatesRoute,
  ColdStorageRoute: ColdStorageRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  CropCalendarRoute: CropCalendarRoute,
  CropInsuranceRoute: CropInsuranceRoute,
  InternshipsRoute: InternshipsRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  MachinesToolsRoute: MachinesToolsRouteWithChildren,
  MarketRoute: MarketRoute,
  MarketPricesRoute: MarketPricesRoute,
  MarketplaceRoute: MarketplaceRoute,
  MyApplicationsRoute: MyApplicationsRoute,
  MyCoursesRoute: MyCoursesRoute,
  NotificationsRoute: NotificationsRoute,
  OrderRoute: OrderRoute,
  RegisterRoute: RegisterRoute,
  SchemesRoute: SchemesRoute,
  SellerRoute: SellerRoute,
  SupportRoute: SupportRoute,
  WeatherRoute: WeatherRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
